// 📚 المقررات المحددة مسبقاً - الخطة الدراسية لقسم نظم المعلومات الإدارية
// جامعة الملك خالد - كلية إدارة الأعمال
// 49 مقرراً موزعة على 8 مستويات

export interface PredefinedCourse {
  code: string;
  name: string;
  name_ar?: string;
  name_en: string;
  credits: number;
  credit_hours?: number;
  level: number;
  is_required: boolean;
  course_type?: 'mandatory' | 'elective';
  prerequisites: string[];
  category: string;
  category_en: string;
  description?: string;
  description_ar?: string;
  description_en?: string;
}

export const PREDEFINED_COURSES: PredefinedCourse[] = [
  // ============================================
  // 📘 المستوى الأول (Level 1) - 6 مقررات
  // ============================================
  {
    code: 'MIS101',
    name: 'مقدمة في نظم المعلومات الإدارية',
    name_ar: 'مقدمة في نظم المعلومات الإدارية',
    name_en: 'Introduction to Management Information Systems',
    credits: 3,
    credit_hours: 3,
    level: 1,
    is_required: true,
    course_type: 'mandatory',
    prerequisites: [],
    category: 'نظم معلومات',
    category_en: 'Information Systems',
    description: 'مقدمة في المفاهيم الأساسية لنظم المعلومات الإدارية',
    description_ar: 'مقدمة في المفاهيم الأساسية لنظم المعلومات الإدارية',
    description_en: 'Introduction to basic concepts of MIS'
  },
  {
    code: 'CS101',
    name: 'مقدمة في الحاسب الآلي',
    name_ar: 'مقدمة في الحاسب الآلي',
    name_en: 'Introduction to Computer Science',
    credits: 3,
    credit_hours: 3,
    level: 1,
    is_required: true,
    course_type: 'mandatory',
    prerequisites: [],
    category: 'علوم حاسب',
    category_en: 'Computer Science',
    description: 'المفاهيم الأساسية للحاسب الآلي ومكوناته',
    description_ar: 'المفاهيم الأساسية للحاسب الآلي ومكوناته',
    description_en: 'Basic computer concepts and components'
  },
  {
    code: 'MATH101',
    name: 'الرياضيات للأعمال',
    name_ar: 'الرياضيات للأعمال',
    name_en: 'Mathematics for Business',
    credits: 3,
    credit_hours: 3,
    level: 1,
    is_required: true,
    course_type: 'mandatory',
    prerequisites: [],
    category: 'رياضيات',
    category_en: 'Mathematics',
    description: 'الرياضيات الأساسية المطلوبة لإدارة الأعمال',
    description_ar: 'الرياضيات الأساسية المطلوبة لإدارة الأعمال',
    description_en: 'Basic mathematics required for business management'
  },
  {
    code: 'ENGL101',
    name: 'اللغة الإنجليزية (1)',
    name_ar: 'اللغة الإنجليزية (1)',
    name_en: 'English Language (1)',
    credits: 3,
    credit_hours: 3,
    level: 1,
    is_required: true,
    course_type: 'mandatory',
    prerequisites: [],
    category: 'لغات',
    category_en: 'Languages',
    description: 'مهارات اللغة الإنجليزية الأساسية',
    description_ar: 'مهارات اللغة الإنجليزية الأساسية',
    description_en: 'Basic English language skills'
  },
  {
    code: 'ARAB101',
    name: 'اللغة العربية',
    name_ar: 'اللغة العربية',
    name_en: 'Arabic Language',
    credits: 2,
    credit_hours: 2,
    level: 1,
    is_required: true,
    course_type: 'mandatory',
    prerequisites: [],
    category: 'لغات',
    category_en: 'Languages',
    description: 'مهارات اللغة العربية والكتابة',
    description_ar: 'مهارات اللغة العربية والكتابة',
    description_en: 'Arabic language and writing skills'
  },
  {
    code: 'ISL101',
    name: 'الثقافة الإسلامية',
    name_ar: 'الثقافة الإسلامية',
    name_en: 'Islamic Culture',
    credits: 2,
    credit_hours: 2,
    level: 1,
    is_required: true,
    course_type: 'mandatory',
    prerequisites: [],
    category: 'دراسات إسلامية',
    category_en: 'Islamic Studies',
    description: 'المفاهيم الأساسية للثقافة الإسلامية',
    description_ar: 'المفاهيم الأساسية للثقافة الإسلامية',
    description_en: 'Basic concepts of Islamic culture'
  },

  // ============================================
  // 📗 المستوى الثاني (Level 2) - 6 مقررات
  // ============================================
  {
    code: 'MIS201',
    name: 'برمجة الأعمال',
    name_ar: 'برمجة الأعمال',
    name_en: 'Business Programming',
    credits: 3,
    credit_hours: 3,
    level: 2,
    is_required: true,
    course_type: 'mandatory',
    prerequisites: ['CS101'],
    category: 'برمجة',
    category_en: 'Programming',
    description: 'أساسيات البرمجة لتطبيقات الأعمال',
    description_ar: 'أساسيات البرمجة لتطبيقات الأعمال',
    description_en: 'Programming basics for business applications'
  },
  {
    code: 'MIS202',
    name: 'قواعد البيانات',
    name_ar: 'قواعد البيانات',
    name_en: 'Database Management',
    credits: 3,
    credit_hours: 3,
    level: 2,
    is_required: true,
    course_type: 'mandatory',
    prerequisites: ['MIS101'],
    category: 'قواعد بيانات',
    category_en: 'Database',
    description: 'تصميم وإدارة قواعد البيانات',
    description_ar: 'تصميم وإدارة قواعد البيانات',
    description_en: 'Database design and management'
  },
  {
    code: 'ACCT201',
    name: 'مبادئ المحاسبة',
    name_ar: 'مبادئ المحاسبة',
    name_en: 'Principles of Accounting',
    credits: 3,
    credit_hours: 3,
    level: 2,
    is_required: true,
    course_type: 'mandatory',
    prerequisites: [],
    category: 'محاسبة',
    category_en: 'Accounting',
    description: 'المبادئ الأساسية للمحاسبة المالية',
    description_ar: 'المبادئ الأساسية للمحاسبة المالية',
    description_en: 'Basic principles of financial accounting'
  },
  {
    code: 'MGMT201',
    name: 'مبادئ الإدارة',
    name_ar: 'مبادئ الإدارة',
    name_en: 'Principles of Management',
    credits: 3,
    credit_hours: 3,
    level: 2,
    is_required: true,
    course_type: 'mandatory',
    prerequisites: [],
    category: 'إدارة',
    category_en: 'Management',
    description: 'المفاهيم الأساسية للإدارة',
    description_ar: 'المفاهيم الأساسية للإدارة',
    description_en: 'Basic management concepts'
  },
  {
    code: 'STAT201',
    name: 'الإحصاء للأعمال',
    name_ar: 'الإحصاء للأعمال',
    name_en: 'Statistics for Business',
    credits: 3,
    credit_hours: 3,
    level: 2,
    is_required: true,
    course_type: 'mandatory',
    prerequisites: ['MATH101'],
    category: 'إحصاء',
    category_en: 'Statistics',
    description: 'الطرق الإحصائية في الأعمال',
    description_ar: 'الطرق الإحصائية في الأعمال',
    description_en: 'Statistical methods in business'
  },
  {
    code: 'ENGL201',
    name: 'اللغة الإنجليزية (2)',
    name_ar: 'اللغة الإنجليزية (2)',
    name_en: 'English Language (2)',
    credits: 3,
    credit_hours: 3,
    level: 2,
    is_required: true,
    course_type: 'mandatory',
    prerequisites: ['ENGL101'],
    category: 'لغات',
    category_en: 'Languages',
    description: 'مهارات اللغة الإنجليزية المتقدمة',
    description_ar: 'مهارات اللغة الإنجليزية المتقدمة',
    description_en: 'Advanced English language skills'
  },

  // ============================================
  // 📙 المستوى الثالث (Level 3) - 6 مقررات
  // ============================================
  {
    code: 'MIS301',
    name: 'تحليل وتصميم النظم',
    name_ar: 'تحليل وتصميم النظم',
    name_en: 'Systems Analysis and Design',
    credits: 3,
    credit_hours: 3,
    level: 3,
    is_required: true,
    course_type: 'mandatory',
    prerequisites: ['MIS201'],
    category: 'تحليل نظم',
    category_en: 'Systems Analysis',
    description: 'منهجيات تحليل وتصميم نظم المعلومات',
    description_ar: 'منهجيات تحليل وتصميم نظم المعلومات',
    description_en: 'IS analysis and design methodologies'
  },
  {
    code: 'MIS302',
    name: 'الشبكات والاتصالات',
    name_ar: 'الشبكات والاتصالات',
    name_en: 'Networks and Communications',
    credits: 3,
    credit_hours: 3,
    level: 3,
    is_required: true,
    course_type: 'mandatory',
    prerequisites: ['CS101'],
    category: 'شبكات',
    category_en: 'Networks',
    description: 'أساسيات شبكات الحاسب والاتصالات',
    description_ar: 'أساسيات شبكات الحاسب والاتصالات',
    description_en: 'Computer networks and communications basics'
  },
  {
    code: 'MIS303',
    name: 'برمجة الويب',
    name_ar: 'برمجة الويب',
    name_en: 'Web Programming',
    credits: 3,
    credit_hours: 3,
    level: 3,
    is_required: true,
    course_type: 'mandatory',
    prerequisites: ['MIS201'],
    category: 'برمجة',
    category_en: 'Programming',
    description: 'تطوير تطبيقات الويب',
    description_ar: 'تطوير تطبيقات الويب',
    description_en: 'Web application development'
  },
  {
    code: 'ECON301',
    name: 'مبادئ الاقتصاد',
    name_ar: 'مبادئ الاقتصاد',
    name_en: 'Principles of Economics',
    credits: 3,
    credit_hours: 3,
    level: 3,
    is_required: true,
    course_type: 'mandatory',
    prerequisites: [],
    category: 'اقتصاد',
    category_en: 'Economics',
    description: 'المبادئ الأساسية للاقتصاد',
    description_ar: 'المبادئ الأساسية للاقتصاد',
    description_en: 'Basic economic principles'
  },
  {
    code: 'MKT301',
    name: 'مبادئ التسويق',
    name_ar: 'مبادئ التسويق',
    name_en: 'Principles of Marketing',
    credits: 3,
    credit_hours: 3,
    level: 3,
    is_required: true,
    course_type: 'mandatory',
    prerequisites: ['MGMT201'],
    category: 'تسويق',
    category_en: 'Marketing',
    description: 'أساسيات التسويق والمزيج التسويقي',
    description_ar: 'أساسيات التسويق والمزيج التسويقي',
    description_en: 'Marketing basics and marketing mix'
  },
  {
    code: 'FIN301',
    name: 'الإدارة المالية',
    name_ar: 'الإدارة المالية',
    name_en: 'Financial Management',
    credits: 3,
    credit_hours: 3,
    level: 3,
    is_required: true,
    course_type: 'mandatory',
    prerequisites: ['ACCT201'],
    category: 'مالية',
    category_en: 'Finance',
    description: 'إدارة الموارد المالية',
    description_ar: 'إدارة الموارد المالية',
    description_en: 'Managing financial resources'
  },

  // ============================================
  // 📕 المستوى الرابع (Level 4) - 6 مقررات
  // ============================================
  {
    code: 'MIS401',
    name: 'إدارة قواعد البيانات المتقدمة',
    name_ar: 'إدارة قواعد البيانات المتقدمة',
    name_en: 'Advanced Database Management',
    credits: 3,
    credit_hours: 3,
    level: 4,
    is_required: true,
    course_type: 'mandatory',
    prerequisites: ['MIS202'],
    category: 'قواعد بيانات',
    category_en: 'Database',
    description: 'المفاهيم المتقدمة لإدارة قواعد البيانات',
    description_ar: 'المفاهيم المتقدمة لإدارة قواعد البيانات',
    description_en: 'Advanced database management concepts'
  },
  {
    code: 'MIS402',
    name: 'نظم دعم القرار',
    name_ar: 'نظم دعم القرار',
    name_en: 'Decision Support Systems',
    credits: 3,
    credit_hours: 3,
    level: 4,
    is_required: true,
    course_type: 'mandatory',
    prerequisites: ['MIS301', 'STAT201'],
    category: 'نظم معلومات',
    category_en: 'Information Systems',
    description: 'نظم دعم اتخاذ القرارات الإدارية',
    description_ar: 'نظم دعم اتخاذ القرارات الإدارية',
    description_en: 'Systems supporting managerial decisions'
  },
  {
    code: 'MIS403',
    name: 'إدارة المشاريع التقنية',
    name_ar: 'إدارة المشاريع التقنية',
    name_en: 'IT Project Management',
    credits: 3,
    credit_hours: 3,
    level: 4,
    is_required: true,
    course_type: 'mandatory',
    prerequisites: ['MIS301'],
    category: 'إدارة مشاريع',
    category_en: 'Project Management',
    description: 'إدارة مشاريع تقنية المعلومات',
    description_ar: 'إدارة مشاريع تقنية المعلومات',
    description_en: 'Managing IT projects'
  },
  {
    code: 'MIS404',
    name: 'أمن المعلومات',
    name_ar: 'أمن المعلومات',
    name_en: 'Information Security',
    credits: 3,
    credit_hours: 3,
    level: 4,
    is_required: true,
    course_type: 'mandatory',
    prerequisites: ['MIS302'],
    category: 'أمن معلومات',
    category_en: 'Security',
    description: 'حماية وأمن نظم المعلومات',
    description_ar: 'حماية وأمن نظم المعلومات',
    description_en: 'Protection and security of IS'
  },
  {
    code: 'HRM401',
    name: 'إدارة الموارد البشرية',
    name_ar: 'إدارة الموارد البشرية',
    name_en: 'Human Resource Management',
    credits: 3,
    credit_hours: 3,
    level: 4,
    is_required: true,
    course_type: 'mandatory',
    prerequisites: ['MGMT201'],
    category: 'موارد بشرية',
    category_en: 'HR',
    description: 'إدارة وتطوير الموارد البشرية',
    description_ar: 'إدارة وتطوير الموارد البشرية',
    description_en: 'Managing and developing human resources'
  },
  {
    code: 'LAW401',
    name: 'القانون التجاري',
    name_ar: 'القانون التجاري',
    name_en: 'Commercial Law',
    credits: 2,
    credit_hours: 2,
    level: 4,
    is_required: true,
    course_type: 'mandatory',
    prerequisites: [],
    category: 'قانون',
    category_en: 'Law',
    description: 'الأسس القانونية للأعمال التجارية',
    description_ar: 'الأسس القانونية للأعمال التجارية',
    description_en: 'Legal foundations of commercial business'
  },

  // ============================================
  // 📔 المستوى الخامس (Level 5) - 6 مقررات
  // ============================================
  {
    code: 'MIS501',
    name: 'نظم المعلومات الاستراتيجية',
    name_ar: 'نظم المعلومات الاستراتيجية',
    name_en: 'Strategic Information Systems',
    credits: 3,
    credit_hours: 3,
    level: 5,
    is_required: true,
    course_type: 'mandatory',
    prerequisites: ['MIS402'],
    category: 'نظم معلومات',
    category_en: 'Information Systems',
    description: 'استخدام نظم المعلومات للميزة التنافسية',
    description_ar: 'استخدام نظم المعلومات للميزة التنافسية',
    description_en: 'Using IS for competitive advantage'
  },
  {
    code: 'MIS502',
    name: 'تطبيقات الأعمال الإلكترونية',
    name_ar: 'تطبيقات الأعمال الإلكترونية',
    name_en: 'E-Business Applications',
    credits: 3,
    credit_hours: 3,
    level: 5,
    is_required: true,
    course_type: 'mandatory',
    prerequisites: ['MIS303', 'MKT301'],
    category: 'أعمال إلكترونية',
    category_en: 'E-Business',
    description: 'تطبيقات التجارة الإلكترونية',
    description_ar: 'تطبيقات التجارة الإلكترونية',
    description_en: 'E-commerce applications'
  },
  {
    code: 'MIS503',
    name: 'تحليل البيانات وذكاء الأعمال',
    name_ar: 'تحليل البيانات وذكاء الأعمال',
    name_en: 'Data Analytics and Business Intelligence',
    credits: 3,
    credit_hours: 3,
    level: 5,
    is_required: true,
    course_type: 'mandatory',
    prerequisites: ['MIS401', 'STAT201'],
    category: 'تحليل بيانات',
    category_en: 'Data Analytics',
    description: 'تحليل البيانات واستخراج المعرفة',
    description_ar: 'تحليل البيانات واستخراج المعرفة',
    description_en: 'Data analysis and knowledge extraction'
  },
  {
    code: 'MIS504',
    name: 'نظم تخطيط موارد المؤسسات (ERP)',
    name_ar: 'نظم تخطيط موارد المؤسسات (ERP)',
    name_en: 'Enterprise Resource Planning (ERP)',
    credits: 3,
    credit_hours: 3,
    level: 5,
    is_required: true,
    course_type: 'mandatory',
    prerequisites: ['MIS402'],
    category: 'نظم معلومات',
    category_en: 'Information Systems',
    description: 'نظم ERP وتطبيقاتها',
    description_ar: 'نظم ERP وتطبيقاتها',
    description_en: 'ERP systems and applications'
  },
  {
    code: 'MIS505',
    name: 'إدارة علاقات العملاء (CRM)',
    name_ar: 'إدارة علاقات العملاء (CRM)',
    name_en: 'Customer Relationship Management (CRM)',
    credits: 3,
    credit_hours: 3,
    level: 5,
    is_required: true,
    course_type: 'mandatory',
    prerequisites: ['MKT301'],
    category: 'إدارة علاقات',
    category_en: 'CRM',
    description: 'إدارة علاقات العملاء إلكترونياً',
    description_ar: 'إدارة علاقات العملاء إلكترونياً',
    description_en: 'Electronic customer relationship management'
  },
  {
    code: 'RES501',
    name: 'مناهج البحث العلمي',
    name_ar: 'مناهج البحث العلمي',
    name_en: 'Research Methodology',
    credits: 2,
    credit_hours: 2,
    level: 5,
    is_required: true,
    course_type: 'mandatory',
    prerequisites: [],
    category: 'بحث علمي',
    category_en: 'Research',
    description: 'أساسيات البحث العلمي',
    description_ar: 'أساسيات البحث العلمي',
    description_en: 'Scientific research basics'
  },

  // ============================================
  // 📓 المستوى السادس (Level 6) - 6 مقررات
  // ============================================
  {
    code: 'MIS601',
    name: 'إدارة نظم المعلومات',
    name_ar: 'إدارة نظم المعلومات',
    name_en: 'Information Systems Management',
    credits: 3,
    credit_hours: 3,
    level: 6,
    is_required: true,
    course_type: 'mandatory',
    prerequisites: ['MIS501'],
    category: 'إدارة نظم',
    category_en: 'Systems Management',
    description: 'إدارة موارد تقنية المعلومات',
    description_ar: 'إدارة موارد تقنية المعلومات',
    description_en: 'Managing IT resources'
  },
  {
    code: 'MIS602',
    name: 'الحوسبة السحابية',
    name_ar: 'الحوسبة السحابية',
    name_en: 'Cloud Computing',
    credits: 3,
    credit_hours: 3,
    level: 6,
    is_required: true,
    course_type: 'mandatory',
    prerequisites: ['MIS302'],
    category: 'حوسبة سحابية',
    category_en: 'Cloud Computing',
    description: 'تقنيات وخدمات الحوسبة السحابية',
    description_ar: 'تقنيات وخدمات الحوسبة السحابية',
    description_en: 'Cloud computing technologies and services'
  },
  {
    code: 'MIS603',
    name: 'تطبيقات الهاتف المحمول',
    name_ar: 'تطبيقات الهاتف المحمول',
    name_en: 'Mobile Applications',
    credits: 3,
    credit_hours: 3,
    level: 6,
    is_required: true,
    course_type: 'mandatory',
    prerequisites: ['MIS303'],
    category: 'برمجة',
    category_en: 'Programming',
    description: 'تطوير تطبيقات الهاتف المحمول',
    description_ar: 'تطوير تطبيقات الهاتف المحمول',
    description_en: 'Mobile app development'
  },
  {
    code: 'MIS604',
    name: 'الذكاء الاصطناعي في الأعمال',
    name_ar: 'الذكاء الاصطناعي في الأعمال',
    name_en: 'Artificial Intelligence in Business',
    credits: 3,
    credit_hours: 3,
    level: 6,
    is_required: true,
    course_type: 'mandatory',
    prerequisites: ['MIS503'],
    category: 'ذكاء اصطناعي',
    category_en: 'AI',
    description: 'تطبيقات الذكاء الاصطناعي في الأعمال',
    description_ar: 'تطبيقات الذكاء الاصطناعي في الأعمال',
    description_en: 'AI applications in business'
  },
  {
    code: 'MIS605',
    name: 'تدقيق نظم المعلومات',
    name_ar: 'تدقيق نظم المعلومات',
    name_en: 'Information Systems Audit',
    credits: 3,
    credit_hours: 3,
    level: 6,
    is_required: true,
    course_type: 'mandatory',
    prerequisites: ['MIS404'],
    category: 'تدقيق',
    category_en: 'Audit',
    description: 'تدقيق ومراجعة نظم المعلومات',
    description_ar: 'تدقيق ومراجعة نظم المعلومات',
    description_en: 'IS auditing and review'
  },
  {
    code: 'ELEC601',
    name: 'مقرر اختياري (1)',
    name_ar: 'مقرر اختياري (1)',
    name_en: 'Elective Course (1)',
    credits: 3,
    credit_hours: 3,
    level: 6,
    is_required: false,
    course_type: 'elective',
    prerequisites: [],
    category: 'مقررات اختيارية',
    category_en: 'Electives',
    description: 'مقرر اختياري من خارج التخصص',
    description_ar: 'مقرر اختياري من خارج التخصص',
    description_en: 'Elective course outside major'
  },

  // ============================================
  // 📒 المستوى السابع (Level 7) - 6 مقررات
  // ============================================
  {
    code: 'MIS701',
    name: 'الحكومة الإلكترونية',
    name_ar: 'الحكومة الإلكترونية',
    name_en: 'E-Government',
    credits: 3,
    credit_hours: 3,
    level: 7,
    is_required: true,
    course_type: 'mandatory',
    prerequisites: ['MIS502'],
    category: 'حكومة إلكترونية',
    category_en: 'E-Government',
    description: 'تطبيقات الحكومة الإلكترونية',
    description_ar: 'تطبيقات الحكومة الإلكترونية',
    description_en: 'E-government applications'
  },
  {
    code: 'MIS702',
    name: 'إدارة المعرفة',
    name_ar: 'إدارة المعرفة',
    name_en: 'Knowledge Management',
    credits: 3,
    credit_hours: 3,
    level: 7,
    is_required: true,
    course_type: 'mandatory',
    prerequisites: ['MIS601'],
    category: 'إدارة معرفة',
    category_en: 'Knowledge Management',
    description: 'إدارة ومشاركة المعرفة المؤسسية',
    description_ar: 'إدارة ومشاركة المعرفة المؤسسية',
    description_en: 'Managing and sharing organizational knowledge'
  },
  {
    code: 'MIS703',
    name: 'إنترنت الأشياء (IoT)',
    name_ar: 'إنترنت الأشياء (IoT)',
    name_en: 'Internet of Things (IoT)',
    credits: 3,
    credit_hours: 3,
    level: 7,
    is_required: true,
    course_type: 'mandatory',
    prerequisites: ['MIS602'],
    category: 'إنترنت الأشياء',
    category_en: 'IoT',
    description: 'تقنيات وتطبيقات إنترنت الأشياء',
    description_ar: 'تقنيات وتطبيقات إنترنت الأشياء',
    description_en: 'IoT technologies and applications'
  },
  {
    code: 'MIS704',
    name: 'البيانات الضخمة',
    name_ar: 'البيانات الضخمة',
    name_en: 'Big Data',
    credits: 3,
    credit_hours: 3,
    level: 7,
    is_required: true,
    course_type: 'mandatory',
    prerequisites: ['MIS503'],
    category: 'بيانات ضخمة',
    category_en: 'Big Data',
    description: 'تحليل ومعالجة البيانات الضخمة',
    description_ar: 'تحليل ومعالجة البيانات الضخمة',
    description_en: 'Big data analysis and processing'
  },
  {
    code: 'MIS705',
    name: 'أخلاقيات تقنية المعلومات',
    name_ar: 'أخلاقيات تقنية المعلومات',
    name_en: 'IT Ethics',
    credits: 2,
    credit_hours: 2,
    level: 7,
    is_required: true,
    course_type: 'mandatory',
    prerequisites: [],
    category: 'أخلاقيات',
    category_en: 'Ethics',
    description: 'الجوانب الأخلاقية لتقنية المعلومات',
    description_ar: 'الجوانب الأخلاقية لتقنية المعلومات',
    description_en: 'Ethical aspects of IT'
  },
  {
    code: 'ELEC701',
    name: 'مقرر اختياري (2)',
    name_ar: 'مقرر اختياري (2)',
    name_en: 'Elective Course (2)',
    credits: 3,
    credit_hours: 3,
    level: 7,
    is_required: false,
    course_type: 'elective',
    prerequisites: [],
    category: 'مقررات اختيارية',
    category_en: 'Electives',
    description: 'مقرر اختياري من داخل أو خارج التخصص',
    description_ar: 'مقرر اختياري من داخل أو خارج التخصص',
    description_en: 'Elective course inside or outside major'
  },

  // ============================================
  // 📑 المستوى الثامن (Level 8) - 7 مقررات
  // ============================================
  {
    code: 'MIS801',
    name: 'مشروع التخرج (1)',
    name_ar: 'مشروع التخرج (1)',
    name_en: 'Graduation Project (1)',
    credits: 2,
    credit_hours: 2,
    level: 8,
    is_required: true,
    course_type: 'mandatory',
    prerequisites: ['RES501'],
    category: 'مشروع تخرج',
    category_en: 'Graduation Project',
    description: 'الجزء الأول من مشروع التخرج',
    description_ar: 'الجزء الأول من مشروع التخرج',
    description_en: 'First part of graduation project'
  },
  {
    code: 'MIS802',
    name: 'مشروع التخرج (2)',
    name_ar: 'مشروع التخرج (2)',
    name_en: 'Graduation Project (2)',
    credits: 4,
    credit_hours: 4,
    level: 8,
    is_required: true,
    course_type: 'mandatory',
    prerequisites: ['MIS801'],
    category: 'مشروع تخرج',
    category_en: 'Graduation Project',
    description: 'الجزء الثاني والنهائي من مشروع التخرج',
    description_ar: 'الجزء الثاني والنهائي من مشروع التخرج',
    description_en: 'Second and final part of graduation project'
  },
  {
    code: 'MIS803',
    name: 'ريادة الأعمال التقنية',
    name_ar: 'ريادة الأعمال التقنية',
    name_en: 'Technology Entrepreneurship',
    credits: 3,
    credit_hours: 3,
    level: 8,
    is_required: true,
    course_type: 'mandatory',
    prerequisites: ['MIS701'],
    category: 'ريادة أعمال',
    category_en: 'Entrepreneurship',
    description: 'ريادة الأعمال في مجال التقنية',
    description_ar: 'ريادة الأعمال في مجال التقنية',
    description_en: 'Entrepreneurship in technology'
  },
  {
    code: 'MIS804',
    name: 'الأمن السيبراني',
    name_ar: 'الأمن السيبراني',
    name_en: 'Cybersecurity',
    credits: 3,
    credit_hours: 3,
    level: 8,
    is_required: true,
    course_type: 'mandatory',
    prerequisites: ['MIS404', 'MIS605'],
    category: 'أمن سيبراني',
    category_en: 'Cybersecurity',
    description: 'حماية البيانات والأنظمة من التهديدات السيبرانية',
    description_ar: 'حماية البيانات والأنظمة من التهديدات السيبرانية',
    description_en: 'Protecting data and systems from cyber threats'
  },
  {
    code: 'MIS805',
    name: 'التحول الرقمي',
    name_ar: 'التحول الرقمي',
    name_en: 'Digital Transformation',
    credits: 3,
    credit_hours: 3,
    level: 8,
    is_required: true,
    course_type: 'mandatory',
    prerequisites: ['MIS601'],
    category: 'تحول رقمي',
    category_en: 'Digital Transformation',
    description: 'استراتيجيات التحول الرقمي في المؤسسات',
    description_ar: 'استراتيجيات التحول الرقمي في المؤسسات',
    description_en: 'Digital transformation strategies in organizations'
  },
  {
    code: 'TRAIN801',
    name: 'التدريب التعاوني',
    name_ar: 'التدريب التعاوني',
    name_en: 'Cooperative Training',
    credits: 3,
    credit_hours: 3,
    level: 8,
    is_required: true,
    course_type: 'mandatory',
    prerequisites: [],
    category: 'تدريب',
    category_en: 'Training',
    description: 'تدريب عملي في إحدى الشركات أو المؤسسات',
    description_ar: 'تدريب عملي في إحدى الشركات أو المؤسسات',
    description_en: 'Practical training in a company or organization'
  },
  {
    code: 'ELEC801',
    name: 'مقرر اختياري (3)',
    name_ar: 'مقرر اختياري (3)',
    name_en: 'Elective Course (3)',
    credits: 3,
    credit_hours: 3,
    level: 8,
    is_required: false,
    course_type: 'elective',
    prerequisites: [],
    category: 'مقررات اختيارية',
    category_en: 'Electives',
    description: 'مقرر اختياري متقدم',
    description_ar: 'مقرر اختياري متقدم',
    description_en: 'Advanced elective course'
  }
];

// ✅ التحقق من صحة البيانات
console.log(`✅ [PredefinedCourses] Loaded ${PREDEFINED_COURSES.length} courses`);

// ✅ التحقق من عدد المقررات في كل مستوى
export const getCoursesByLevel = (level: number): PredefinedCourse[] => {
  return PREDEFINED_COURSES.filter(course => course.level === level);
};

// ✅ إحصائيات المقررات
export const COURSES_STATS = {
  total: PREDEFINED_COURSES.length,
  required: PREDEFINED_COURSES.filter(c => c.is_required).length,
  elective: PREDEFINED_COURSES.filter(c => !c.is_required).length,
  byLevel: {
    1: getCoursesByLevel(1).length,
    2: getCoursesByLevel(2).length,
    3: getCoursesByLevel(3).length,
    4: getCoursesByLevel(4).length,
    5: getCoursesByLevel(5).length,
    6: getCoursesByLevel(6).length,
    7: getCoursesByLevel(7).length,
    8: getCoursesByLevel(8).length,
  }
};